# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{ system ? builtins.currentSystem, pkgs, lib, fetchurl, installShellFiles }:
let
  shaMap = {
    i686-linux = "06y7cr4n2w2wp9d4mn7rhbn9qsxwbfnmd6n1qapyr71c6cs9pa6q";
    x86_64-linux = "0vq0003l2qv3l736yzh3w11hbykffxdiqjbp0prjz2fcb63giwzm";
    aarch64-linux = "1jp6rchxs497gsj0bx5vhw2yhjzywsvp15ibm7fbg5xjldjzaq0v";
    x86_64-darwin = "08vyj03m7v2dgfdgacqyhn3hn2s4qqyxiyvv1vh3nm7h0m350cjm";
    aarch64-darwin = "0f9bnarin8myj59f89qb36sdfbwf7q423lwlaa23kgvv5c86mpal";
  };

  urlMap = {
    i686-linux = "https://github.com/elwin/franz/releases/download/v1.0.11/franz_Linux_i386.tar.gz";
    x86_64-linux = "https://github.com/elwin/franz/releases/download/v1.0.11/franz_Linux_x86_64.tar.gz";
    aarch64-linux = "https://github.com/elwin/franz/releases/download/v1.0.11/franz_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/elwin/franz/releases/download/v1.0.11/franz_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/elwin/franz/releases/download/v1.0.11/franz_Darwin_arm64.tar.gz";
  };
in pkgs.stdenv.mkDerivation {
  pname = "franz";
  version = "1.0.11";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./franz $out/bin/franz
  '';

  system = system;

  meta = with lib; {
    description = "Your Swiss-Army Knife tool for interacting with Kafka.";
    homepage = "https://github.com/elwin/franz";

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
