# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{ system ? builtins.currentSystem, pkgs, lib, fetchurl, installShellFiles }:
let
  shaMap = {
    i686-linux = "14chsfqggndzwawcsgaxxd31z1wx2jn19sv45mdj0bg0k9nz92fq";
    x86_64-linux = "1fij3cnqjhmrbxshiyvxi785hh1if5rry2h7495v8q8q06cz9vzj";
    aarch64-linux = "0w911qjf2278m29hwna49bc02fhw6ivsj1rm7c4cw0fgvsbqns0z";
    x86_64-darwin = "17pdi0nl28hh0jffx46j1zlmb8pjrrdc1q7kl0lz56ihpyl97fgx";
    aarch64-darwin = "0fc8m156gy5r1wdxj9pdlwd7pimmqap7qfkr01bqflgaaaibzygz";
  };

  urlMap = {
    i686-linux = "https://github.com/elwin/franz/releases/download/v2.0.0/franz_Linux_i386.tar.gz";
    x86_64-linux = "https://github.com/elwin/franz/releases/download/v2.0.0/franz_Linux_x86_64.tar.gz";
    aarch64-linux = "https://github.com/elwin/franz/releases/download/v2.0.0/franz_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/elwin/franz/releases/download/v2.0.0/franz_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/elwin/franz/releases/download/v2.0.0/franz_Darwin_arm64.tar.gz";
  };
in pkgs.stdenv.mkDerivation {
  pname = "franz";
  version = "2.0.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./franz $out/bin/franz
  '';

  system = system;

  meta = with lib; {
    description = "Your Swiss-Army Knife tool for interacting with Kafka.";
    homepage = "https://github.com/elwin/franz";

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
